# format = """\
# ${username}\
# ${hostname}\
# ${directory}\
# ${cmd_duration}\
# ${character}\
# """

format = '''
[â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€>](bold blue)
[â”‚](bold blue)  $username$hostname$directory$git_branch
[â”‚](bold blue)
[â””â”€>](bold blue) '''

right_format = '''$cmd_duration'''

add_newline = true

[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = true

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[âœ](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "[âœ—](bold red)"

# configure directory
[directory]
read_only = " ï ½"
truncation_length = 10
truncate_to_repo = true # truncates directory to root folder if in github repo
style = "bold italic blue"

[hostname]
ssh_only = false
format = 'on [$hostname](bold purple) '
trim_at = "."
disabled = false

[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = false
style = "bold italic red"


[battery]
full_symbol = 'ğŸ”‹ '
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€ '

[git_branch]
symbol = 'ğŸŒ± '
style = 'bold yellow'
format = 'on [$symbol$branch(:$remote_branch)]($style) '

